services:
  server:
    image: app-backend
    build:
      context: app-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - app-backend/.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/chatapp

  app:
    image: app-frontend
    build:
      context: app-frontend
      dockerfile: Dockerfile
    ports:
      - 5173:3000
    environment:
      - VITE_API_URL=http://localhost:8080

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatapp
    volumes:
      - ./app-backend/postgres-data/prod/:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 8080:80
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server