services:
  app-backend:
    image: app-backend
    build:
      context: app-backend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - app-backend/.env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/chatapp

  app-frontend:
    image: app-frontend
    build:
      context: app-frontend
      dockerfile: dev.Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatapp
    volumes:
      - ./app-backend/postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 8080:80
    container_name: reverse-proxy
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-frontend
      - app-backend